//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cards
    {
        public Cards()
        {
            this.Players = new HashSet<Players>();
            this.Players1 = new HashSet<Players>();
            this.Players2 = new HashSet<Players>();
            this.Players3 = new HashSet<Players>();
            this.Players4 = new HashSet<Players>();
        }
    
        public int Id { get; set; }
        public int suit { get; set; }
        public int value { get; set; }
    
        public virtual ICollection<Players> Players { get; set; }
        public virtual ICollection<Players> Players1 { get; set; }
        public virtual ICollection<Players> Players2 { get; set; }
        public virtual ICollection<Players> Players3 { get; set; }
        public virtual ICollection<Players> Players4 { get; set; }
    }
}
