//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public Games()
        {
            this.Players = new HashSet<Players>();
            this.ThrownCards = new HashSet<ThrownCards>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public int pool { get; set; }
        public int turns { get; set; }
        public int totalTurns { get; set; }
    
        public virtual ICollection<Players> Players { get; set; }
        public virtual ICollection<ThrownCards> ThrownCards { get; set; }
    }
}
