//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int Id { get; set; }
        public int card1 { get; set; }
        public int card2 { get; set; }
        public int card3 { get; set; }
        public int card4 { get; set; }
        public int card5 { get; set; }
        public int money { get; set; }
        public int prevBet { get; set; }
        public bool myTurn { get; set; }
    
        public virtual Cards Cards { get; set; }
        public virtual Cards Cards1 { get; set; }
        public virtual Cards Cards2 { get; set; }
        public virtual Cards Cards3 { get; set; }
        public virtual Cards Cards4 { get; set; }
    }
}
