//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public int Id { get; set; }
        public int card1_suit { get; set; }
        public int card1_value { get; set; }
        public int card2_suit { get; set; }
        public int card2_value { get; set; }
        public int card3_suit { get; set; }
        public int card3_value { get; set; }
        public int card4_suit { get; set; }
        public int card4_value { get; set; }
        public int card5_suit { get; set; }
        public int card5_value { get; set; }
        public int money { get; set; }
        public int prevBet { get; set; }
        public bool myTurn { get; set; }
        public int totalBet { get; set; }
        public int game { get; set; }
    
        public virtual Games Games { get; set; }
    }
}
