//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poker
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThrownCards
    {
        public int Id { get; set; }
        public int suit { get; set; }
        public int value { get; set; }
        public int game { get; set; }
    
        public virtual Games Games { get; set; }
    }
}
